name: Build Executables

on:
  push:
    tags:
      - 'v*'  # trigger only on tags like v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller customtkinter

      - name: Build executable
        run: |
          pyinstaller --name UniversalFileCollector --onefile main.py

      - name: Prepare release directory
        run: |
          mkdir release

      - name: Rename and move executable
        shell: bash
        run: |
          OS_NAME="${{ runner.os }}"
          EXT=""
          if [ "$OS_NAME" = "Windows" ]; then
            EXT=".exe"
          elif [ "$OS_NAME" = "macOS" ]; then
            EXT=""  # pyinstaller produces binary without .app by default
          elif [ "$OS_NAME" = "Linux" ]; then
            EXT=""
          fi
          # The built executable path:
          SRC="dist/UniversalFileCollector${EXT}"
          # Destination path:
          DEST="release/UniversalFileCollector-${OS_NAME}${EXT}"

          echo "Moving $SRC to $DEST"
          mv "$SRC" "$DEST"

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
